name: Publish docker image

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy build to azure app service
        default: false
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DB_URI: ${{ secrets.DATABASE_CONNECTION_STRING }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ vars.TEST_NODE_ENV }}
      TEST_TIMEOUT: ${{ vars.TEST_TIMEOUT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Testing the application
        run: |
          npm install
          npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to azure app service
        if: inputs.deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: shadow-archive
          images: leanderpaul/shadow-archive@${{ steps.docker-build.outputs.Digest }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
